#!/usr/bin/env tsx
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  architecturalMetrics,
  scanComponents,
  scanImportBoundaries,
  scanOversizedFiles,
  scanRoutes,
  ROOT,
} from "./lib/scan-repo";

const REPORT_DIR = join(ROOT, ".local/reports");
const GENERATED_DIR = join(ROOT, "docs/generated");

function writeReport(name: string, body: string) {
  const path = join(REPORT_DIR, name);
  writeFileSync(path, body, "utf8");
  console.log(`wrote ${path}`);
}

function writeGenerated(name: string, body: string) {
  mkdirSync(GENERATED_DIR, { recursive: true });
  const path = join(GENERATED_DIR, name);
  const content = `<!-- generated by pnpm foundry:report — do not edit -->\n\n${body}`;
  writeFileSync(path, content, "utf8");
  console.log(`wrote ${path}`);
}

mkdirSync(REPORT_DIR, { recursive: true });

const generatedAt = new Date().toISOString();
const metrics = architecturalMetrics();
const boundaries = scanImportBoundaries();
const oversized = scanOversizedFiles();
const routes = scanRoutes();
const components = scanComponents();

// --- oversized-files.md ---
writeReport(
  "oversized-files.md",
  [
    "# Oversized files",
    "",
    `Generated: ${generatedAt}`,
    "",
    oversized.length === 0
      ? "All files within contract limits."
      : oversized.map((o) => `- \`${o.file}\`: ${o.lines} lines (max ${o.max})`).join("\n"),
  ].join("\n"),
);

// --- import-boundaries.md ---
writeReport(
  "import-boundaries.md",
  [
    "# Import boundaries",
    "",
    `Generated: ${generatedAt}`,
    `Files scanned: ${boundaries.filesScanned}`,
    "",
    "## Violations",
    "",
    boundaries.violations.length === 0
      ? "None."
      : boundaries.violations.map((v) => `- ${v}`).join("\n"),
    "",
    "## Most imported modules",
    "",
    metrics.topImports.map((i) => `- \`${i.target}\` (${i.count})`).join("\n"),
  ].join("\n"),
);

// --- dependency-summary.md ---
let depSection = "_pnpm outdated unavailable_\n";
try {
  depSection = execSync("pnpm outdated --format list 2>/dev/null || true", {
    encoding: "utf8",
    cwd: ROOT,
  }).trim() || "(all dependencies current or registry unreachable)";
} catch {
  /* ignore */
}

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

writeReport(
  "dependency-summary.md",
  [
    "# Dependency summary",
    "",
    `Generated: ${generatedAt}`,
    "",
    "## Production dependencies",
    "",
    ...Object.entries(pkg.dependencies ?? {}).map(([k, v]) => `- ${k}: ${v}`),
    "",
    "## Dev dependencies",
    "",
    ...Object.entries(pkg.devDependencies ?? {}).map(([k, v]) => `- ${k}: ${v}`),
    "",
    "## Outdated (pnpm outdated)",
    "",
    "```",
    depSection,
    "```",
  ].join("\n"),
);

// --- route-map.md ---
writeReport(
  "route-map.md",
  [
    "# Route map",
    "",
    `Generated: ${generatedAt}`,
    "",
    "| Path | Type | File |",
    "|------|------|------|",
    ...routes.map((r) => `| \`${r.path}\` | ${r.type} | \`${r.file}\` |`),
  ].join("\n"),
);

writeGenerated(
  "routes.md",
  [
    "# Routes inventory",
    "",
    `Generated: ${generatedAt}`,
    "",
    "| Path | Type | File |",
    "|------|------|------|",
    ...routes.map((r) => `| \`${r.path}\` | ${r.type} | \`${r.file}\` |`),
  ].join("\n"),
);

// --- components inventory ---
writeGenerated(
  "components.md",
  [
    "# Components inventory",
    "",
    `Generated: ${generatedAt}`,
    "",
    "| Component | Client | Lines | File |",
    "|-----------|--------|-------|------|",
    ...components.map(
      (c) => `| ${c.name} | ${c.client ? "yes" : "no"} | ${c.lines} | \`${c.file}\` |`,
    ),
  ].join("\n"),
);

// --- architecture-report.md ---
writeReport(
  "architecture-report.md",
  [
    "# Architecture report",
    "",
    `Generated: ${generatedAt}`,
    "",
    "## Metrics",
    "",
    "| Metric | Value |",
    "|--------|------:|",
    `| App routes (pages) | ${metrics.routeCount} |`,
    `| API routes | ${metrics.apiRouteCount} |`,
    `| Layouts | ${metrics.layoutCount} |`,
    `| Components | ${metrics.componentCount} |`,
    `| Client components | ${metrics.clientComponentCount} |`,
    `| Server action files | ${metrics.serverActionFiles} |`,
    `| lib/flux modules | ${metrics.libFluxFiles} |`,
    `| Oversized files | ${metrics.oversizedCount} |`,
    `| Import boundary violations | ${boundaries.violations.length} |`,
    "",
    "## Largest files",
    "",
    metrics.largestFiles.map((f) => `- \`${f.file}\`: ${f.lines} lines`).join("\n"),
    "",
    "## Reports",
    "",
    "- [import-boundaries.md](./import-boundaries.md)",
    "- [oversized-files.md](./oversized-files.md)",
    "- [dependency-summary.md](./dependency-summary.md)",
    "- [route-map.md](./route-map.md)",
    "",
    "## Generated docs",
    "",
    "- [docs/generated/routes.md](../docs/generated/routes.md)",
    "- [docs/generated/components.md](../docs/generated/components.md)",
    "",
    "## Enforcement",
    "",
    "Run `pnpm check:graph` for circular imports and dependency-cruiser rules.",
  ].join("\n"),
);

console.log("\nFoundry report complete.");
